Cmseibel
Revature-Sophia-ECommerce-1376/e-commerce-backend pull request #88
Opened 2022-07-31 16:24 UTC by CameronMSeibel

Expands existing unit testing in services for increased coverage

2022-07-31 17:33 UTC, acarasimon96 requested changes
Failure messages need tweaking, but this looks great to me otherwise

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/AddressServiceTest.java
> +			fail("Expected an exception to be thrown");
You should specify which exception type is expected to be thrown. In this case, it's `AddressNotFoundException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/ProductServiceTest.java
> +			fail("Expected an exception to be throw");
You should specify which exception type is expected to be thrown. In this case, it's `ProductNotFoundException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/ProductServiceTest.java
> +			fail("Expected an exception to be thrown");
You should specify which exception type is expected to be thrown. In this case, it's `ProductNotFoundException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/PurchaseServiceTest.java
> +			fail("Expected exception to be thrown");
You should specify which exception type is expected to be thrown. In this case, it's `UserNotFoundException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/ReviewServiceTest.java
> +			fail("Expected an exception to be thrown");
You should specify which exception type is expected to be thrown. In this case, it's `DuplicateReviewException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/ReviewServiceTest.java
> +			fail("Expected an exception to be thrown");
You should specify which exception type is expected to be thrown. In this case, it's `ReviewNotFoundException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/UserServiceTest.java
> +			assertEquals(UserNotFoundException.class, e.getClass());
You should specify which exception type is expected to be thrown. In this case, it's `UserNotFoundException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/UserServiceTest.java
> +			fail("Expected an exception to be thrown");
You should specify which exception type is expected to be thrown. In this case, it's `UserNotFoundException`

2022-07-31 17:33 UTC, acarasimon96 commented on src/test/java/com/revature/services/UserServiceTest.java
> +			this.uServ.findByEmail(email);
You forgot to add the following line after:
```java
fail("Expected UserNotFoundException to be thrown");
```

2022-08-01 17:32 UTC, CameronMSeibel commented
Implemented changes to service fail messages, may want to hold off on merging this branch until the controller tests work again. Currently can't build with test failures, so I can't generate a coverage report

2022-08-01 17:32 UTC, closed without merging